# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ics < Formula
  desc "Convert jira ticket to ics file"
  homepage "https://github.com/iandri/ics"
  version "0.0.10"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iandri/ics/releases/download/v0.0.10/ics_0.0.10_Darwin_arm64.tar.gz"
      sha256 "777a2c6cecb4ec9ef502d2e972e0791e8e941cd1658dc1e6c2e9c2f8bd364688"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.10/ics_0.0.10_Darwin_x86_64.tar.gz"
      sha256 "bdf29eeaa3591a7318223498656d34b7ecb6a4bdac429a0980b45cc91d814221"

      def install
        bin.install "ics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.10/ics_0.0.10_Linux_x86_64.tar.gz"
      sha256 "e1b5ec190e5e636244385afe9f2a7b76c640277f693ec635e0af693d8082c7ad"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iandri/ics/releases/download/v0.0.10/ics_0.0.10_Linux_arm64.tar.gz"
      sha256 "abdc4e665ec65db08b082be41251eb9fa6e82e30cb56ea4fb03d0ff392cf0e4e"

      def install
        bin.install "ics"
      end
    end
  end
end
