# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ics < Formula
  desc "Convert jira ticket to ics file"
  homepage "https://github.com/iandri/ics"
  version "0.0.13"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iandri/ics/releases/download/v0.0.13/ics_0.0.13_Darwin_arm64.tar.gz"
      sha256 "1cf3dfdf796b92e41ee241ce402525e064cc2341436caa8820ab412f731d283f"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.13/ics_0.0.13_Darwin_x86_64.tar.gz"
      sha256 "61a91d0ff75fedfa9441d8b7f6f8175625b54f4f2b8c3db64f40165e0b738101"

      def install
        bin.install "ics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iandri/ics/releases/download/v0.0.13/ics_0.0.13_Linux_arm64.tar.gz"
      sha256 "27a1e1c124a759f4baf8163ee85e7bd177743e8fa6f7e449a8f668d0bdef15ac"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.13/ics_0.0.13_Linux_x86_64.tar.gz"
      sha256 "6b2b724c89c69930270e6d3001cf6583bcaed9c2050aeee1a784f034770d4f85"

      def install
        bin.install "ics"
      end
    end
  end
end
