# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ics < Formula
  desc "Convert jira ticket to ics file"
  homepage "https://github.com/iandri/homebrew-taps"
  version "0.0.8"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iandri/ics/releases/download/v0.0.8/ics_0.0.8_Darwin_arm64.tar.gz"
      sha256 "c9baf2a14239e11380be07e348b1f9201e6fa805673c17a6c8bb04e559f730bd"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.8/ics_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "e19a98229359a3e4cd0d0962182f382b89192ccbad95d1a81343d5aa4f025452"

      def install
        bin.install "ics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iandri/ics/releases/download/v0.0.8/ics_0.0.8_Linux_arm64.tar.gz"
      sha256 "b0d668e74231366a5da581134200a6a4f37b5f135bf46a5ffb92e53c0f6d455c"

      def install
        bin.install "ics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iandri/ics/releases/download/v0.0.8/ics_0.0.8_Linux_x86_64.tar.gz"
      sha256 "f39390c3408fff74297e5d1e09396377b15080e00981b7574d5ca30926527a8e"

      def install
        bin.install "ics"
      end
    end
  end
end
